### ISSUE TITLE
MOVEABLE Input Bug

### ISSUE THREAD

**Issue by cmr624** [GreatGrandmaGames/GrandmaAssetPackages#5]
Since the Moveable class' .Move() function is called in a MoveController, it is called in a FixedUpdate because it is applying physics changes. We are also calculating the input vector during this fixedupdate, which is fine for an axis that directly apply forces to the RB but not for direct input polls like buttons being pressed down, this has led to some input loss.

**Comment by elliot-winch** [comment]
use Input.GetKeyDown(KeyCode.LeftControl) at any time - ie inside InputVectorCalculation

**Comment by cmr624** [comment]
That doesn’t work if it’s in FixedUpdate, it should only be in Update bc fixed update is called every physics tick, no? And we want every frame bc the system could miss the input

**Comment by cmr624** [comment]
Yeah we use GetButtonDown for jump

**Comment by elliot-winch** [comment]
Wasn't aware of this limitation. Let me make the following changes to rectify: 

Moveable: active.InputVectorCalculation in called in Update, which sets a private Vector3 in the MoveController class

MoveController: uses most recent inoput vector for calculations

**Comment by cmr624** [comment]
It’s weird tho, bc I looked it up and modifying the RB directly via input you want in FixedUpdate, but “event-like” polling (GetKeyDown) should be done in Update. If you want we can discuss tmrw / when we meet

**Comment by cmr624** [comment]
Going to solve this by writing an Input class

**Comment by elliot-winch** [comment]
Discussed. Resolved by careful design, rather than developmental base.

**Comment by cmr624** [comment]
we should just take "jump" out of movement and add it as an ability. movement should be strictly how a player moves at all times when the component is active

**Comment by elliot-winch** [comment]
Much smort. That’s a good idea I like it

**Comment by cmr624** [comment]
fixed by making jump an ability, gives us more flexibility and separates from the movement system.
